// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TodoAPI.Models;

public partial class Todo
{
    [Key]
    [Column("todoId")]
    public int TodoId { get; set; }

    [Required]
    [Column("title")]
    [StringLength(50)]
    [Unicode(false)]
    public string Title { get; set; }

    [Required]
    [Column("description")]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("completed")]
    public bool? Completed { get; set; } = false;

    [Column("userId")]
    public int UserId { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Todos")]
    public virtual User User { get; set; }
}